name: "Create Daily plan Issue"
description: "automatic create daily english issue for nick19910321/study-every-day-english"
inputs:
  token: 
    description: "github token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
